language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

jdk:
  - oraclejdk8
